### ISSUE TITLE
Cannot add Reviewer to PR once github-actions is added as a reviewer

### ISSUE THREAD

**Issue by neilgierman** [microsoft/vscode-pull-request-github#6443]
Type: <b>Bug</b>

Our repo has a validation workflow using `jesusvasquez333/verify-pr-label-action` to make sure we have included the appropriate labels on PRs. Once that workflow runs `github-actions` will add either an approval or request-changes to the PR.

The problem is once github-actions is added as a reviewer to the PR, if I try to add another reviewer via this VSCode extension, I get an error of:
```
[error] GraphQL error: Variable $input of type RequestReviewsInput! was provided invalid value for userIds.0 (Expected value to not be null)
```

To work around this, I either need to add all of my reviewers before the label-checker runs, or add reviewers via the GitHub web UI.

Extension version: 0.100.0
VS Code version: Code 1.95.0 (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 6.8.0-47-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700T CPU @ 2.40GHz (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.79GB (1.69GB free)|
|Process Argv|--crash-reporter-id e70f73ff-3995-4cec-ab96-4386bd2cc49f|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: neil-HP-ZBook-15-G3.attlocal.net|
|OS|Linux x64 6.8.0-47-generic|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 799)|
|Memory (System)|15.50GB (12.36GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
iacca2:31156134
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31164048
icondisabled:31158250

```

</details>

**Comment by JayDeline** [comment]
Dont install anything but GitHub

**Comment by alexr00** [comment]
To verify:
1. Install the latest pre-release version of GitHub Pull Requests
2. Open a folder containing a clone of a GitHub repo in VS Code
3. Open a PR description from the Pull Requests view
4. Add a bot as a reviewer and verify on github.com that the reviewer was added.
5. Go back to  VS Code and add a non-bot as a reviewer
6. Verify on github.com that both the bot and non-bot are both listed as reviewers.

**Comment by TylerLeonhardt** [comment]
So I set up a repo with `jesusvasquez333/verify-pr-label-action`... basically here's my Actions file:
```
name: "Auto-Label PR"
permissions:
  pull-requests: write
  issues: write
  contents: read
  checks: write
  statuses: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Verify Pull Request Labels
        uses: jesusvasquez333/verify-pr-label-action@v1.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          valid-labels: "bug,feature,enhancement,refactor,documentation,tests,dependencies,ci,performance,security"
          invalid-labels: "wontfix,invalid,question,duplicate,help wanted,good first issue"
          pull-request-number: ${{ github.event.pull_request.number }}
          disable-reviews: false
```

I could see the bot being added:
<img width="1230" alt="image" src="https://github.com/user-attachments/assets/a5e14cf0-72de-4a70-82d0-2ae907e95e65" />

and when I add another reviewer I do see GitHub-actions there:
<img width="666" alt="image" src="https://github.com/user-attachments/assets/5b0dacdd-204b-475b-a9a5-d2bcebdcecab" />

but when I select Rob, here's what I get:
<img width="497" alt="image" src="https://github.com/user-attachments/assets/779307fc-9c7a-43cd-b5de-32db3acd3aaf" />

and he is not added.
